"""init core tables: users, companies, scraped_jobs

Revision ID: ef8d8186f1f9
Revises: 
Create Date: 2026-04-16 12:24:52.602789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef8d8186f1f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('size_range', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hiring_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraped_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('remote_type', sa.String(length=50), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), server_default='USD', nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_source', sa.String(length=20), server_default='aggregator', nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('score_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('match_keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('suggested_variant', sa.String(length=50), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='new', nullable=True),
    sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('idx_jobs_score', 'scraped_jobs', [sa.text('relevance_score DESC')], unique=False)
    op.create_index('idx_jobs_scraped_at', 'scraped_jobs', [sa.text('scraped_at DESC')], unique=False)
    op.create_index('idx_jobs_source', 'scraped_jobs', ['source'], unique=False)
    op.create_index('idx_jobs_status', 'scraped_jobs', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index('idx_jobs_status', table_name='scraped_jobs')
    op.drop_index('idx_jobs_source', table_name='scraped_jobs')
    op.drop_index('idx_jobs_scraped_at', table_name='scraped_jobs')
    op.drop_index('idx_jobs_score', table_name='scraped_jobs')
    op.drop_table('scraped_jobs')
    op.drop_table('companies')
    # ### end Alembic commands ###
