"""add applications, cv, email, config, agent, apify, portfolio tables

Revision ID: f087c407b308
Revises: ef8d8186f1f9
Create Date: 2026-04-17 04:21:52.870388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f087c407b308'
down_revision: Union[str, None] = 'ef8d8186f1f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('progress_pct', sa.Integer(), server_default='0', nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('progress_log', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('process_pid', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apify_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('api_token', sa.String(length=500), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=True),
    sa.Column('monthly_credit_usd', sa.Numeric(precision=10, scale=2), server_default='5.00', nullable=True),
    sa.Column('credit_used_usd', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('quota_reset_at', sa.DateTime(), nullable=True),
    sa.Column('exhausted_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_apify_cooldown', 'apify_accounts', ['cooldown_until'], unique=False)
    op.create_index('idx_apify_status', 'apify_accounts', ['status', 'priority'], unique=False)
    op.create_table('master_cv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_markdown', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('source_type', sa.String(length=20), server_default='manual', nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('source_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('variant_target', sa.String(length=50), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('excluded_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('locations', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('job_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('remote_only', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('sources', postgresql.ARRAY(sa.String()), server_default='{remoteok,hn_algolia,hiring_cafe,adzuna,arbeitnow,jobspy}', nullable=True),
    sa.Column('max_results_per_source', sa.Integer(), server_default='30', nullable=True),
    sa.Column('cron_expression', sa.String(length=50), server_default='0 */3 * * *', nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apify_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('compute_units', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('jobs_scraped', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['apify_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_account', 'apify_usage_log', ['account_id', sa.text('created_at DESC')], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='targeting', nullable=True),
    sa.Column('targeted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('interview_at', sa.DateTime(), nullable=True),
    sa.Column('offered_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('applied_via', sa.String(length=50), nullable=True),
    sa.Column('applied_url', sa.String(length=1000), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_title', sa.String(length=255), nullable=True),
    sa.Column('salary_asked', sa.Integer(), nullable=True),
    sa.Column('salary_offered', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('cv_id', sa.Integer(), nullable=True),
    sa.Column('email_draft_id', sa.Integer(), nullable=True),
    sa.Column('cover_letter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['scraped_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_app_dates', 'applications', [sa.text('applied_at DESC')], unique=False)
    op.create_index('idx_app_status', 'applications', ['status'], unique=False)
    op.create_table('portfolio_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relevance_hint', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('display_priority', sa.Integer(), server_default='50', nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=True),
    sa.Column('auto_generated', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', sa.String(length=100), nullable=True),
    sa.Column('new_value', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cover_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=30), server_default='professional', nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['scraped_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('email_type', sa.String(length=30), server_default='initial', nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.Column('personalization', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['scraped_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_cvs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('master_cv_id', sa.Integer(), nullable=True),
    sa.Column('tailored_markdown', sa.Text(), nullable=True),
    sa.Column('tailored_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('docx_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.Column('keyword_matches', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('missing_keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variant_used', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('generation_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['scraped_jobs.id'], ),
    sa.ForeignKeyConstraint(['master_cv_id'], ['master_cv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_cvs')
    op.drop_table('email_drafts')
    op.drop_table('cover_letters')
    op.drop_table('application_activities')
    op.drop_table('portfolio_assets')
    op.drop_index('idx_app_status', table_name='applications')
    op.drop_index('idx_app_dates', table_name='applications')
    op.drop_table('applications')
    op.drop_index('idx_usage_account', table_name='apify_usage_log')
    op.drop_table('apify_usage_log')
    op.drop_table('scrape_configs')
    op.drop_table('master_cv')
    op.drop_index('idx_apify_status', table_name='apify_accounts')
    op.drop_index('idx_apify_cooldown', table_name='apify_accounts')
    op.drop_table('apify_accounts')
    op.drop_table('agent_jobs')
    # ### end Alembic commands ###
